DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS saved CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE,
  password_digest VARCHAR(255)
);

CREATE TABLE saved (
  id SERIAL PRIMARY KEY,
  itemname VARCHAR(100),
  calories REAL,
  saved_id INTEGER REFERENCES users(id)
);
