# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a66b669e89330e514f9616d1ac154356511977422b48daf828a5fecba598fbbb8d6ddad0884146a75d6571075092c7bf4fc94f86f2b8c68f674bfd26a00c5d10

test:
  secret_key_base: 70c60a9907d13137eede87642e22bb55ee6e61fc8870e65adfc349abdd7b5ce93e664d897114cd9608cfdeba4f0794ab215e37ec77d5333749f23c1bbc244fa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
